### ISSUE TITLE
Import rules from `ember-best-practices`

### ISSUE THREAD

**Issue by Turbo87** [netguru/eslint-plugin-ember#10]
see https://github.com/chadhietala/ember-best-practices

**Comment by michalsnik** [comment]
I would totally love to import some of those rules here. I'll try to speak with @chadhietala about this.
Actually the final goal of this project is to integrate all of those great rules in one place. Thanks for pointing this repository @Turbo87!

**Comment by michalsnik** [comment]
I created separate issues for importing missing rules from `ember-best-practices`, see #51, #52, #53 
Thus I'm closing this ticket and we'll continue discussion there. 

The rest of the rules has already been implemented, but has different names:
`no-lifecycle-events` -> `no-on-calls-in-components`
`require-dependent-keys` -> `no-unused-dependent-properties` (in progress - it's not that simple)
`no-side-effect-cp` -> `no-side-effects`
`no-observers` -> `no-observers`
