### ISSUE TITLE
Improve "order-in-*" rule warnings

### ISSUE THREAD

**Issue by Turbo87** [netguru/eslint-plugin-ember#13]
Currently the rules only state "Check order of properties", but we should try to be more helpful and tell the user if the property should be moved up or down, possibly even a line number.

**Comment by michalsnik** [comment]
True, that would make total sense and it's for sure worth considering. Current message indeed might be confusing..

Not sure though if I'll be able to work on this right now, but if anyone wants to help, we would really appreciate it :)

**Comment by Turbo87** [comment]
@michalsnik have a look at https://github.com/netguru/eslint-plugin-ember/issues/15 😉

**Comment by michalsnik** [comment]
Damn, apparently I'm blind! I just realised when looking into open PRs. This is awesome! I'll look at this hopefully today, eventually tomorrow. Great work @Turbo87 :)

**Comment by michalsnik** [comment]
Released as https://github.com/netguru/eslint-plugin-ember/releases/tag/v2.1.0
