### ISSUE TITLE
Contribution

### ISSUE THREAD

**Issue by craigbilner** [netguru/eslint-plugin-ember#14]
Hi, I'm currently moving our codebase to conform to your eslint rules and am writing some codemods that people may find useful.

So far I've adapted Tom Dale's [module codemod](https://github.com/tomdale/ember-modules-codemod) to handle your `local-modules` and `use-ember-get-and-set` rules. I've also created [one](https://github.com/craigbilner/ember-on-codemod) for your `no-on-calls-in-components` rule and [one](https://github.com/craigbilner/ember-braces-codemod) for your `use-brace-expansion` rule.

Any feedback is welcome and let me know if the codemod doesn't align to the rule!

**Comment by Turbo87** [comment]
@craigbilner why don't you convert those to ESLint fix code so that we can use it via `eslint --fix`?

**Comment by craigbilner** [comment]
Thanks @Turbo87, unfortunately `fix` isn't really designed for these sort of large modifications. The [guidelines](http://eslint.org/docs/developer-guide/working-with-rules#applying-fixes) suggest making only small changes (such as one token) so that they don't collide with other eslint rules/fixes. Also the fix method isn't as powerful as `jscodeshift`/`recast`.

**Comment by michalsnik** [comment]
Hey @craigbilner , this is great. I'm sure at point we can mention about that in this repository so that everyone can move their projects towards better practices in a more convenient way. So far so good :)

**Comment by craigbilner** [comment]
@michalsnik sweet. I've now got preliminary [named-functions-in-promises](https://github.com/craigbilner/ember-name-promise-codemod) and [order-in-components](https://github.com/craigbilner/ember-comp-order-codemod) going. Feel free to close this issue and raise any feedback on them, ta.

**Comment by michalsnik** [comment]
Cool @craigbilner, sure thing 👍
