### ISSUE TITLE
alias-model-in-controller not working via route controller setup

### ISSUE THREAD

**Issue by cinkonaap** [netguru/eslint-plugin-ember#21]
`alias-model-in-controller` rule in documentation has an ability to be covered by setting model in route's `setupController` method. This is not working, and even is not intended to, so it should be removed from documentation.

Anyway, I hope there was some way to cover such scenarios. We have cases when our controller do not have model (this may be misconception on legacy code level, and can be 'not-so-easily' converted to components or something else). But what about case, when I do want stay with `model` property name?

**Comment by michalsnik** [comment]
The documentation is maybe not that clear about this. But the intent was that if you have a controller, you should alias your model there. But if you don't have a separate controller, but rather a simple `setupController()` in route, then you can set it there (it will be not checked though, it's still a legit rule that you can follow). If you however would like to use `model` property on your controller, then in your case you should probably disable this rule in this controller using `eslint-disable ember/alias-model-in-controller`, or globally in `.eslintrc.js`.

**Comment by cinkonaap** [comment]
I think disabling the rule in specific controller is reasonable in that case. Thanks for response 👍

**Comment by michalsnik** [comment]
No problem :)
