### ISSUE TITLE
order-in-controllers vs query-params-on-top

### ISSUE THREAD

**Issue by michalsnik** [netguru/eslint-plugin-ember#29]
@davidpett encountered an issue (originally discussed in #23) with both of those rules turned on. On of which requires setting `queryParams` on the very top of a controller, but `order-in-controllers` rule wants service injections first.That leads to a clear problem.

My first thought is to add `queryParams` in `order-in-controllers` rule as the next thing after service injections (to be consistent) and getting rid of `query-params-on-top` (or at least disabling it in default as well as in recommended config).
That way if anyone would want to change order in his controllers he can do so in eslint's configuration.

Not sure right now if there is a better way of handling this though.

To be discussed.
cc @jbandura @kevinkucharczyk @netes @bardzusny @davidpett

**Comment by davidpett** [comment]
Is it possible to check for rules within another rule?

**Comment by michalsnik** [comment]
I'm not sure to be honest @davidpett

**Comment by netes** [comment]
Removing `query-params-on-top` and including it in `order-in-controllers` would be a good move, but I'm not convinced that the query params should stick on the top. To be consistent with the rest of ordering rules I would leave injections first, followed by `queryParams`. WDYT?

**Comment by michalsnik** [comment]
That sounds like a reasonable approach @netes. I'm on it right now :)

**Comment by jbandura** [comment]
+1 to what @netes said

**Comment by michalsnik** [comment]
Version `v3.0.0` has been released 🎉 @davidpett we removed `query-params-on-top` rule and introduced improved order in controllers as discussed above. Feel free to check this out :)
https://github.com/netguru/eslint-plugin-ember/releases/tag/v3.0.0
