### ISSUE TITLE
order-in-models + services?

### ISSUE THREAD

**Issue by bdmac** [netguru/eslint-plugin-ember#41]
The changes to `order-in-models` rule seem to want services injected in models to appear at the bottom of the model. This seems like a strange departure since other ordering rules want services to be at the top. Also the example does not show a way to customize where services should appear like in the `order-in-controllers` rule so I'm not sure if that's even an option or not.

**Comment by michalsnik** [comment]
Hey @bdmac, thanks for pointing this.
Indeed we might want to add this in one of next PRs.

For now you can customize this rule like this:

```
ember/order-in-models: [2, {
  order: [
    'service',
    'attribute',
    'relationship',
    'single-line-function',
    'multi-line-function',
  ]
}]
```

You can find list of all detectable things here: https://github.com/netguru/eslint-plugin-ember/blob/master/lib/utils/property-order.js#L10

I hope this solves your problem.

**Comment by bdmac** [comment]
It will indeed. I just wasn't clear if those detections were applicable in all contexts or if they were somehow specific to each type. E.g. it wasn't clear I could detect services in models.

**Comment by michalsnik** [comment]
Okay, then I think we should update documentation to be more specific about this :)
