### ISSUE TITLE
New rule proposal - "no-capital-letters-in-routes"

### ISSUE THREAD

**Issue by netes** [netguru/eslint-plugin-ember#48]
According to this issue: https://github.com/emberjs/ember.js/issues/15108 I think it's worth to add such rule.

In short: raise an error when there is a route with uppercased letters in `router.js`.

@snik @jbandura @bardzusny @kevinkucharczyk what do you think guys?

**Comment by jbandura** [comment]
:+1: should definitely help with late-night debugging sessions ;)

**Comment by michalsnik** [comment]
If this is something that raises issues in Ember, then I think we should add this rule. It makes perfect sense to me 👍  Would you like to proceed with this @netes?

**Comment by netes** [comment]
Sure thing :)

**Comment by michalsnik** [comment]
Released in `3.4.1`
