### ISSUE TITLE
Compatibility with yeoman generator for eslint

### ISSUE THREAD

**Issue by michalsnik** [netguru/eslint-plugin-ember#5]
Currently this plugin is not compatible with yeoman generator for eslint: https://github.com/eslint/generator-eslint

New rule is being created in wrong directory instead of the one with other rules.

To be: This plugin's folder structure should be the one recommended in mentioned generator, so that creating new rules with `yo eslint:rule` is flawless.

**Comment by alexlafroscia** [comment]
Do you want to change the way the documentation is done, too? The Yeoman generator has a rule per file, matching the way ESLint itself does the documentation.

**Comment by alexlafroscia** [comment]
Also, I'm happy to take this little task on myself.

**Comment by michalsnik** [comment]
I think it makes perfect sense @alexlafroscia , not only because of the yeoman generated structure, but because of the number of different rules we have here. It will be easier to manage separate docs for each rule instead of one giant documentation.

What do you think @netes? You were working on current documentation.

Also we have to remember about creating PR to https://github.com/jfmengels/eslint-rule-documentation after this is implemented :)

Be my guest @alexlafroscia  :) That makes me even more happier

**Comment by alexlafroscia** [comment]
Cool, feel free to assign me. I took a night off from OSS last night but will do this at some point between now and Monday.

**Comment by netes** [comment]
@michalsnik, I think it's a perfect idea, as our rule set is pretty big and it's constantly growing. Thanks for contribution @alexlafroscia!
