### ISSUE TITLE
`use-ember-get-and-set` warns on non-Ember `get`s

### ISSUE THREAD

**Issue by SaladFork** [netguru/eslint-plugin-ember#57]
For example, if you are [declaring a GET route in Ember CLI Mirage](http://www.ember-cli-mirage.com/docs/v0.3.x/route-handlers/#shorthands):

```javascript
// Throws `use-ember-get-and-set` linting error
this.get('/foo', (db) => {
server.get('/foo', (db) => {
```

Or using `this.set` in [an integration test](https://guides.emberjs.com/v2.12.0/testing/testing-components/):
```javascript
this.set('person', { name: 'Foo' });
```

**Comment by michalsnik** [comment]
I think it's related to #28

**Comment by SaladFork** [comment]
Thanks! Added some thoughts [on #55](https://github.com/netguru/eslint-plugin-ember/pull/55#issuecomment-296210385).

**Comment by michalsnik** [comment]
I'm closing this as I proposed solution in #28 and we can continue this discussion there.
