### ISSUE TITLE
Error running `ember` @ 2.6.2 with addon installed

### ISSUE THREAD

**Issue by utilityboy** [netguru/eslint-plugin-ember#72]
I have an application running ember 2.6.2 and after installing `eslint-plugin-ember` I'm met with the following:

```
ember s --proxy
An addon must define a `name` property.
```

Is there anything I'm missing here?  I took a brief look at the dependencies for the addon and nothing jumped out at me.

Many thanks.

**Comment by nfc036** [comment]
I have the same problem with ember-cli@2.13.2 and eslint-plugin-ember@3.4.0. 

My current workaround: eslint-plugin-ember@3.3.0 is ok.

**Comment by michalsnik** [comment]
Hey, version `3.4.1` fixed this problem, check it out.

**Comment by nfc036** [comment]
I can confirm that 3.4.1 is working as expected. Thank you!
